### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by drbrx** [VoltDevelopers/Simulation-lotto#36]
- [x] Grafici: bug di scala (se credito iniziale e' troppo grande);
- [x] Mettere cosa sono gli assi (tramite TextView)
- [x] Cambiare colore della menu
- [x] Refactor recursion func
- [x] Fare sesta linea del banco
- [x] File save for android 10+
- [x] Settnigs: eliminare la possibilita' di chiuderlo
- [x] Check inputs
- [x] Revisione toString (?)
- [x] Revisione testo
- [x] Code Clean
- [x] Revisione logo
- [x] Fare in readme moduli: come funziona random usato, templine del progetto, scema del progetto, roba tecnica per AndroidStudio (versione, sdk ,...)
- [ ] Fare il grafico dinamico
- [x] Creare Release
- [x] Fare presentazione
